project:
  type: website
  output-dir: docs   

website:
  title: "MUH Portfolio"
  site-url: "https://manditatiana.github.io/Portfolio/"
  repo-url: "https://github.com/manditatiana/Portfolio"
  repo-actions: [edit, issue]
  page-footer: 
   left: "Updated Apr 24, 2025" 
  navbar:
    background: primary
    search: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: about.qmd

  sidebar:
    - title: "Projects"
      style: "docked"
      background: dark
      contents:
        - about.qmd
        - text: "SAK Law Reform Text Anyalysis"
          href: Datasci.qmd

format:
  html:
    theme:
      - Minty
    css: styles.css
    toc: true



