project:
  type: website
  output-dir: docs   # ⬅️ move this here!

website:
  title: "MUH Portfolio"
  site-url: "https://manditatiana.github.io/Portfolio/"
  repo-url: "https://github.com/manditatiana/Portfolio"
  repo-actions: [edit, issue]
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "Projects"
        href: about.qmd
        contents:
         - Datasci.qmd


format:
  html:
    theme:
      - Minty
    css: styles.css
    toc: true



