project:
  type: website
  output-dir: docs   # ⬅️ move this here!

website:
  title: "Portfolio"
  site-url: "https://manditatiana.github.io/Portfolio/"
  repo-url: "https://github.com/manditatiana/Portfolio"
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
<<<<<<< HEAD
      - text: "Projects"
        menu:
          - href: Datasci.qmd
            text: Data Science Project
=======
      - href: Datasci.qmd
        text: Data Science Project
>>>>>>> refs/remotes/origin/main
      


format:
  html:
    theme:
      - Minty
    css: styles.css
    toc: true



